### ISSUE TITLE
ImportError: cannot import name UnpackedSDist

### ISSUE THREAD

**Issue by gijzelaerr** [ska-sa/katversion#24]
hi! I'm making debian packages for various kat software thingies.  The katversion package is a bit problematic to package though. The debian package system doesn't allow automatic downloading of dependencies, so I have to use the distro version of the packages. in The case of Ubuntu 14.04 this doesn't work. 14.04 is bundled with pkginfo 0.9.1-1, which doesn't seem to work:

```
dpkg-buildpackage
dpkg-buildpackage: source package katversion
dpkg-buildpackage: source version 0.7-1
dpkg-buildpackage: source distribution xenial
dpkg-buildpackage: source changed by Gijs Molenaar (launchpad ppa build key) <gijs@pythonic.nl>
dpkg-buildpackage: host architecture amd64
 dpkg-source --before-build katversion
 fakeroot debian/rules clean
dh clean --with python2,python3 --buildsystem=pybuild
   dh_testdir -O--buildsystem=pybuild
   dh_auto_clean -O--buildsystem=pybuild
	pybuild --clean -i python{version} -p 2.7 --dir .
I: pybuild base:170: python2.7 setup.py clean
Traceback (most recent call last):
  File "setup.py", line 27, in <module>
    from katversion import get_version
  File "/home/gijs/packaging/katversion/katversion/__init__.py", line 17, in <module>
    from .version import get_version, build_info
  File "/home/gijs/packaging/katversion/katversion/version.py", line 30, in <module>
    from pkginfo import UnpackedSDist
ImportError: cannot import name UnpackedSDist
E: pybuild pybuild:256: clean: plugin distutils failed with: exit code=1: python2.7 setup.py clean
dh_auto_clean: pybuild --clean -i python{version} -p 2.7 --dir . returned exit code 13
make: *** [clean] Error 13
dpkg-buildpackage: error: fakeroot debian/rules clean gave error exit status 2
```

**Comment by fjoubert** [comment]
With my limited experience, doing a pip install before trying to package it seemed to work fine. But that might be because we use fpm to build a debian from a python package: `fpm -s python -t deb .` Not Sure if that helps.

**Comment by ludwigschwardt** [comment]
Sure, it looks like `UnpackedSDist` only got added to `pkginfo 1.1b1` (2013-05-05). What do you suggest - to not depend on that class?
