### ISSUE TITLE
Missing pkginfo in requirements

### ISSUE THREAD

**Issue by bennahugo** [ska-sa/katversion#25]
@ludwigschwardt FYI after pulling in changes from katdal master into simon's fixed size storage manager branch we have a missing dependency in katversion:
```
      File "/tmp/easy_install-0OPiiw/katversion-0.7/katversion/__init__.py", line 17, in <module>
      File "/tmp/easy_install-0OPiiw/katversion-0.7/katversion/version.py", line 30, in <module>
    ImportError: No module named pkginfo
```

**Comment by bennahugo** [comment]
Full steps with fix
```
FROM kernsuite/base:3
+FROM stimela/base:0.3.1
 MAINTAINER <sphemakh@gmail.com>
 
 RUN docker-apt-install casacore-dev git python-pip
 RUN docker-apt-install python-casacore
-RUN pip install -I git+https://github.com/sjperkins/katdal@use-python-casacore-ms-creation
+RUN pip install -U pip pkginfo
+RUN pip install -I git+https://github.com/sjperkins/katdal@use-python-casacore-ms-creation#egg=katdal
```

**Comment by ludwigschwardt** [comment]
I don't quite get it - all my attempts at installing `katversion` succeeds. Please state exactly what you did.

We did add a `requirements.txt` to `katdal` after @sjperkins 's branch (mostly so that its first ever unit tests would run on Jenkins). This is the only change that likely precipitates this. The `requirements.txt` already specifies `pkginfo`.

What makes `pkginfo` special is that it is a "pre-setup" requirement of `katversion`. It needs to be installed *before* `katversion`'s `setup.py` can run. To deal with this, `setup.py` installs `pkginfo` internally if not found. So I don't get why that part won't work.

**Comment by lvdheever** [comment]
In our case we are installing katdeploy that has katversion included install_requires in its setup.py on a fresh Ubuntu 14.04 container.

If I do the same with --force-install and dependencies (NOT --no-deps) on an existing container it seems to collect the pkginfo from katversion correctly though?
```
Collecting pkginfo (from katversion->katdeploy==0.1.dev2245+user.lize.cb.2385.c72ee9c)
  Downloading http://pypi.camlab.kat.ac.za/pypi/trusty/+f/31a/49103180ae151/pkginfo-1.4.1-py2.py3-none-any.whl

kat@monctl.devl.camlab.kat.ac.za:~/deployment$ python -c "import katversion; print katversion.__version__"
0.7

kat@monctl.devl.camlab.kat.ac.za:~/deployment$ sudo pip install katversion -U --force-reinstall
The directory '/home/kat/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/kat/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting katversion
  Downloading http://pypi.camlab.kat.ac.za/pypi/trusty/+f/e99/33411534fd394/katversion-0.7-py2.py3-none-any.whl
Collecting pkginfo (from katversion)
  Downloading http://pypi.camlab.kat.ac.za/pypi/trusty/+f/31a/49103180ae151/pkginfo-1.4.1-py2.py3-none-any.whl
Installing collected packages: pkginfo, katversion
  Found existing installation: pkginfo 1.4.1
    Uninstalling pkginfo-1.4.1:
      Successfully uninstalled pkginfo-1.4.1
  Found existing installation: katversion 0.7
    Uninstalling katversion-0.7:
      Successfully uninstalled katversion-0.7
Successfully installed katversion-0.7 pkginfo-1.4.1
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

Will test again on a fresh container to see what is different.

**Comment by lvdheever** [comment]
The test on a fresh container (during fab kat_deploy.install_nodes_by_group:devl2,trunk-requirements.txt) produced the error again. Pasted below. Looks like there is an easy_install in there somewhere?
```
[kat@monctl.devl2.camlab.kat.ac.za] run: git pull
[kat@monctl.devl2.camlab.kat.ac.za] out: Already up-to-date.
[kat@monctl.devl2.camlab.kat.ac.za] out: 

[kat@monctl.devl2.camlab.kat.ac.za] run: git checkout master
[kat@monctl.devl2.camlab.kat.ac.za] out: Already on 'master'
[kat@monctl.devl2.camlab.kat.ac.za] out: Your branch is up-to-date with 'origin/master'.
[kat@monctl.devl2.camlab.kat.ac.za] out: 

[kat@monctl.devl2.camlab.kat.ac.za] sudo: pip install ~/deployment
[kat@monctl.devl2.camlab.kat.ac.za] out: sudo password:
[kat@monctl.devl2.camlab.kat.ac.za] out: The directory '/home/kat/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
[kat@monctl.devl2.camlab.kat.ac.za] out: The directory '/home/kat/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
[kat@monctl.devl2.camlab.kat.ac.za] out: Processing ./deployment
[kat@monctl.devl2.camlab.kat.ac.za] out:     Complete output from command python setup.py egg_info:
[kat@monctl.devl2.camlab.kat.ac.za] out:     Traceback (most recent call last):
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "<string>", line 1, in <module>
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/tmp/pip-mWX_X5-build/setup.py", line 45, in <module>
[kat@monctl.devl2.camlab.kat.ac.za] out:         zip_safe=False,
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 128, in setup
[kat@monctl.devl2.camlab.kat.ac.za] out:         _install_setup_requires(attrs)
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/usr/local/lib/python2.7/dist-packages/setuptools/__init__.py", line 123, in _install_setup_requires
[kat@monctl.devl2.camlab.kat.ac.za] out:         dist.fetch_build_eggs(dist.setup_requires)
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 453, in fetch_build_eggs
[kat@monctl.devl2.camlab.kat.ac.za] out:         replace_conflicting=True,
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 866, in resolve
[kat@monctl.devl2.camlab.kat.ac.za] out:         replace_conflicting=replace_conflicting
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1146, in best_match
[kat@monctl.devl2.camlab.kat.ac.za] out:         return self.obtain(req, installer)
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1158, in obtain
[kat@monctl.devl2.camlab.kat.ac.za] out:         return installer(requirement)
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/usr/local/lib/python2.7/dist-packages/setuptools/dist.py", line 520, in fetch_build_egg
[kat@monctl.devl2.camlab.kat.ac.za] out:         return cmd.easy_install(req)
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 672, in easy_install
[kat@monctl.devl2.camlab.kat.ac.za] out:         return self.install_item(spec, dist.location, tmpdir, deps)
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 698, in install_item
[kat@monctl.devl2.camlab.kat.ac.za] out:         dists = self.install_eggs(spec, download, tmpdir)
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 879, in install_eggs
[kat@monctl.devl2.camlab.kat.ac.za] out:         return self.build_and_install(setup_script, setup_base)
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1118, in build_and_install
[kat@monctl.devl2.camlab.kat.ac.za] out:         self.run_setup(setup_script, setup_base, args)
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1104, in run_setup
[kat@monctl.devl2.camlab.kat.ac.za] out:         run_setup(setup_script, args)
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 257, in run_setup
[kat@monctl.devl2.camlab.kat.ac.za] out:         raise
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
[kat@monctl.devl2.camlab.kat.ac.za] out:         self.gen.throw(type, value, traceback)
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 199, in setup_context
[kat@monctl.devl2.camlab.kat.ac.za] out:         yield
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
[kat@monctl.devl2.camlab.kat.ac.za] out:         self.gen.throw(type, value, traceback)
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 170, in save_modules
[kat@monctl.devl2.camlab.kat.ac.za] out:         saved_exc.resume()
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 145, in resume
[kat@monctl.devl2.camlab.kat.ac.za] out:         six.reraise(type, exc, self._tb)
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 158, in save_modules
[kat@monctl.devl2.camlab.kat.ac.za] out:         yield saved
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 199, in setup_context
[kat@monctl.devl2.camlab.kat.ac.za] out:         yield
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 254, in run_setup
[kat@monctl.devl2.camlab.kat.ac.za] out:         _execfile(setup_script, ns)
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 49, in _execfile
[kat@monctl.devl2.camlab.kat.ac.za] out:         exec(code, globals, locals)
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/tmp/easy_install-OVBGWW/katversion-0.7/setup.py", line 27, in <module>
[kat@monctl.devl2.camlab.kat.ac.za] out:         "scripts/kat-delete-branch.py",
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/tmp/easy_install-OVBGWW/katversion-0.7/katversion/__init__.py", line 17, in <module>
[kat@monctl.devl2.camlab.kat.ac.za] out:       File "/tmp/easy_install-OVBGWW/katversion-0.7/katversion/version.py", line 30, in <module>
[kat@monctl.devl2.camlab.kat.ac.za] out:     ImportError: No module named pkginfo
[kat@monctl.devl2.camlab.kat.ac.za] out:     
[kat@monctl.devl2.camlab.kat.ac.za] out:     ----------------------------------------
[kat@monctl.devl2.camlab.kat.ac.za] out: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-mWX_X5-build/
```

**Comment by ludwigschwardt** [comment]
Try adding `pkginfo` to all relevant `requirements.txt` of packages that need `katversion`, especially if you are installing those from source / GitHub (like @sjperkins branch and `katdeploy`...).

@lvdheever, I notice that `pkginfo` is *not* in `~/deployment/TEMPLATE-requirements.txt`.

**Comment by lvdheever** [comment]
@ludwigschwardt Tx. I will try adding pkginfo to katdeploy requirements. 
But currently it breaks on installing katdeploy long before we start with kat_update.py that uses the generated requirements file from TEMPLATE-requirements.txt

**Comment by ludwigschwardt** [comment]
There is no more `pkginfo` requirement since v0.8.
